# Generated by Django 6.0.3 on 2026-03-25 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='un', max_length=32)),
                ('isbn_normalized', models.CharField(blank=True, default='', max_length=13)),
                ('search_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('trust_status', models.CharField(choices=[('allowed', 'Allowed'), ('review_required', 'Review Required'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], default='review_required', max_length=32)),
                ('is_search_eligible', models.BooleanField(default=False)),
                ('last_healthcheck_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracted', 'Extracted'), ('review_required', 'Review Required'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed'), ('review_required', 'Review Required')], default='pending', max_length=32)),
                ('queried_sources_count', models.PositiveIntegerField(default=0)),
                ('timeout_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to='persistence.canonicalitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='canonicalitem',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='persistence.uploadbatch'),
        ),
        migrations.CreateModel(
            name='VersionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=64)),
                ('version_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['material_id', 'version_number'],
                'constraints': [models.UniqueConstraint(fields=('material_id', 'version_number'), name='uq_version_event_material_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='canonicalitem',
            constraint=models.UniqueConstraint(fields=('upload_batch', 'item_code'), name='uq_canonical_item_batch_code'),
        ),
    ]
