# Generated by Django 6.0.3 on 2026-03-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesite',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sourcesite',
            name='integration_type',
            field=models.CharField(choices=[('api', 'API'), ('scraping', 'Scraping')], default='scraping', max_length=32),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(blank=True, default='', max_length=512)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('product_url', models.URLField(max_length=2048)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('unknown', 'Unknown')], default='new', max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='persistence.canonicalitem')),
                ('search_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='persistence.searchjob')),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='persistence.sourcesite')),
            ],
            options={
                'ordering': ['total_price'],
            },
        ),
        migrations.CreateModel(
            name='SearchExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('empty', 'Empty'), ('timeout', 'Timeout'), ('error', 'Error')], default='ok', max_length=32)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='persistence.searchjob')),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='persistence.sourcesite')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('review_queue', 'Review Queue'), ('draft', 'Draft'), ('brand_approval', 'Brand Approval'), ('export_ready', 'Export Ready'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='persistence.canonicalitem')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
